### ISSUE TITLE
casper-types 4.0.1 does not have the std-fs-io feature flag on crates.io

### ISSUE THREAD

**Issue by marijanp** [casper-ecosystem/casper-client-rs#162]
see https://docs.rs/crate/casper-types/4.0.1/features

**Comment by gRoussac** [comment]
Hi @marijanp std-fs-io is only on `dev` branches right now. dev branches are not using the last release but dev patches

https://github.com/casper-ecosystem/casper-client-rs/blob/dev/Cargo.toml#L53-L55

Were you trying to compile the last released version ? https://github.com/casper-ecosystem/casper-client-rs/tree/v2.0.0 

Closing this ticket let me know if you have further questions.

**Comment by marijanp** [comment]
What is the reason for not having compatible casper crates on crates.io?
