### ISSUE TITLE
[SIDECAR] Remove dependency on `casper-node/binary-port`

### ISSUE THREAD

**Issue by zajko** [casper-ecosystem/casper-client-rs#194]
Currently sidecar has a dependency on `casper-node/binary-port`. Binary port is not a module that we plan to release as a separate library, so we need to copy the types we need from the node to sidecar.

*AC*: 
* Sidecar no longer has a dependency on module `casper-node/binary-port` which is internal to the node

**Comment by devendran-m** [comment]
This issue was created under this repo incorrectly. Therefore closing this issue here and reopening it as a new issue under the sidecar repo - https://github.com/casper-network/casper-sidecar/issues/350.
