### ISSUE TITLE
Add `put-transaction` subcommands for managing delegator reservations

### ISSUE THREAD

**Issue by wojcik91** [casper-ecosystem/casper-client-rs#198]
Add `add-reservations` and `cancel-reservations` subcommands for interactions with new Auction entrypoints.

Note: Add dedicated CLI options for passing in reservations and pass them along to the node as CLType::Any.

**Comment by devendran-m** [comment]
Assign it to Maciej

**Comment by wojcik91** [comment]
Relevant updates to casper-types were implemented in https://github.com/casper-network/casper-node/pull/4971
