### ISSUE TITLE
Short argument "-p" for "--public-key" is broken in recent versions

### ISSUE THREAD

**Issue by GuybrushX** [casper-ecosystem/casper-client-rs#2]
It seems there was some rewrite recently and "-p" isn't an alias for "--public-key" anymore but for "purse-uref" as seen here:
https://github.com/casper-ecosystem/casper-client-rs/blob/a67578a3db3833fe5f9e2e6c511821dffa57a4d3/src/get_balance.rs#L25

I experienced this with version 1.4.1 + 1.4.2. Version 1.3.3 is working.

The casper-client help account-address shows this info:
```
OPTIONS:
    -p, --public-key <FORMATTED STRING or PATH>
            This must be a properly formatted public key. The public key may instead be read in from a file, in which
            case enter the path to the file as the --public-key argument. The file should be one of the two public key
            files generated via the `keygen` subcommand; "public_key_hex" or "public_key.pem"
```

That also breaks the get-auction-info.sh script for providing account details -> I'll file a separate issue there if you can confirm that bug.

Here is the affected line:
https://github.com/make-software/casper-account-info-contract/blob/master/tools/get-account-info.sh#L65

**Comment by Fraser999** [comment]
This appears indeed to have been an oversight during recent refactors.

The `-p` alias can vary from subcommand to subcommand (as you point out, it is an alias for `--purse-uref` in the `get-balance` subcommand, and it's an alias for `--payment-amount` in many of the deploy creation subcommands like `put-deploy`).

We should however be able to reapply the short form to the two subcommands currently using `--public-key`, namely `get-account-info` and `account-address`, as they don't already use the `-p` short form for any other other args.
