### ISSUE TITLE
[Issue] Unable to run casper-client on Mac M1

### ISSUE THREAD

**Issue by cryofracture** [casper-ecosystem/casper-client-rs#46]
Mac M1 users are not able to install casper-client version 1.5.0 installed via `cargo install casper-client`.

## Steps to reproduce
```bash
brew update
xcode-select --install
brew install pkg-config
brew install openssl
cargo install casper-client
```

## What should happen:
casper-client CLI tool should be installed by `cargo`, permitting use of `casper-client` commands like `casper-client -V` or `casper-client get-state-root-hash`

## What actually happens:
All `casper-client` commands result in:
```bash
MacBook:/ user$ casper-client -V
Illegal instruction: 4
```

## Debug info
This is broken using rust nightly.
Rustc:
```
user$ rustc --version
rustc 1.66.0 (69f9c33d7 2022-12-12)
```
Rustup:
```
user$ rustup --version
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.66.0 (69f9c33d7 2022-12-12)`
```
Cargo:
```
user$ cargo --version
cargo 1.66.0 (d65d197ad 2022-11-15)
```
And non-shallow checkout out brew:
```
git -C /usr/local/Homebrew/Library/Taps/homebrew/homebrew-cask fetch --unshallow
```

**Comment by achilovbakhrom** [comment]
same here ((

**Comment by RitaMAllenCA** [comment]
At the moment, we do not support running a node on Mac.   If/when we revisit the OS support we provide, we may revisit the position.  Closing for now.
