### ISSUE TITLE
Improve multisig support in casper-client-rs

### ISSUE THREAD

**Issue by RitaMAllenCA** [casper-ecosystem/casper-client-rs#56]
We should support the creation of deploys where the session account is not automatically derived from the provided secret key.  We should also make the provision of a secret key optional for the `make-deploy` and `make-transfer` subcommands

**Comment by Fraser999** [comment]
Note that updates to support this exist [here](https://github.com/casper-ecosystem/casper-client-rs/commit/45842b808d78259030651c6c80067012a2c6138a), but need the addition of tests before a PR can be cut.

**Comment by RitaMAllenCA** [comment]
2.0.1

**Comment by MParlikar** [comment]
This is a high value feature that has been rolling for several sprints. Needs to be prioritized and tied off.  Please work to get it done.
